apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: claimant-service-default
spec:
  destination:
    name: claimant-service
  precedence: 2
  match:
    request:
      headers:
        cookie:
          regex: "^(.*?;)?(user=jason)(;.*)?$"
  route:
  - labels:
      version: v1
