apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: {{appName}}-default
spec:
  destination:
    name: {{appName}}
  precedence: 2
  match:
    request:
      headers:
        cookie:
          regex: "^(.*?;)?(user=asok)(;.*)?$"
  route:
  - labels:
      version: {{version}}
