apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    sidecar.istio.io/status: {{ .Values.istio.status }}
  creationTimestamp: null
  name: {{ .Values.claimant.name }}-{{ .Chart.Version }}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        sidecar.istio.io/status: {{ .Values.istio.status }}
      creationTimestamp: null
      labels:
        app: {{ .Values.claimant.name }}
        version: {{ .Chart.Version }}
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ .Values.claimant.spring.profiles }}
        image: {{ .Values.claimant.image.name }}
        imagePullPolicy: {{ .Values.claimant.imagePullPolicy }}
        name: {{ .Values.claimant.name }}
        ports:
        - containerPort: {{ .Values.claimant.port }}
        resources: {}
      {{ include "istioproxy" .}}
      {{ include "istioinitcontainers" .}}
      {{ include "istiovolume" .}}
status: {}
---