apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    sidecar.istio.io/status: {{ .Values.istio.status }}
  creationTimestamp: null
  name: {{ index .Values "hello-world" "name" }}-v1
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        sidecar.istio.io/status: {{ .Values.istio.status }}
      creationTimestamp: null
      labels:
        app: {{ index .Values "hello-world" "name" }}
        version: v1
        name: {{ index .Values "hello-world" "name" }}
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ index .Values "hello-world" "spring" "profiles"}}
        image: {{ index .Values "hello-world" "image" "name"}}
        imagePullPolicy: {{ index .Values "hello-world" "imagePullPolicy" }}
        name: {{ index .Values "hello-world" "name" }}
        ports:
        - containerPort: {{ index .Values "hello-world" "port" }}
        resources: {}
      {{ include "istioproxy" .}}
      {{ include "istioinitcontainers" .}}
      {{ include "istiovolume" .}}
status: {}
---