apiVersion: v1
kind: Service
metadata:
  name: {{ index .Values "hello-world" "name" }}
  labels:
    name: {{ index .Values "hello-world" "name" }}
spec:
  ports:
    - port: {{ .Values.helloworldExternalHttpPort }}
      name: http
  selector:
    name: {{ index .Values "hello-world" "name" }}
  type: NodePort