hello-world:
  name: hello-world
  version: v1
  image:
    name: gcr.io/adroit-flare-179614/hello-world-v1
  imagePullPolicy: IfNotPresent
  port: 8081
  spring:
    profiles: dev
claimant-service:
  name: claimant-service
  version: v1
  image:
    name: gcr.io/adroit-flare-179614/claimant-service-v1
  imagePullPolicy: IfNotPresent
  port: 8082
  spring:
    profiles: dev
gateway:
  name: gateway
helloworldExternalHttpPort: 8081
claimantserviceExternalHttpPort: 8082

## Specify a imagePullPolicy
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##


istioImage: docker.io/istio/proxy_debug:0.1

istioImagePullPolicy: Always
istio:
  status: injected-version-root@822a7ac3ca86-0.2.4-9c7c291eab0a522f8033decd0f5b031f5ed0e126
ingress:
  class: istio